package com.xiang.exceptionDemo;

public class ExceptionDemo {
    public static void main(String[] args) {
        int a = 1;
        int b = 0;

//        try {
//            new ExceptionDemo().Test(1,0);
//        } catch (ArithmeticException e) {
//            e.printStackTrace();
//        }
        //捕获多个异常，从小到大捕获。
        //surrounding with hotkey: cmd + atl + T
//        try{
//
//
//        }catch (ArithmeticException e){
//            System.out.println("程序出现异常");
//        }catch (Exception e){
//            System.out.println("Exception");
//        }catch (Throwable t){
//            System.out.println("Throwable");
//        }
//        finally { //always executed
//            System.out.println("finally");
//        }
    }
    //方法上抛出异常
//    public void Test(int a, int b) throws ArithmeticException{
//        if(b==0){
//            throw new ArithmeticException();//主动抛出异常
//        }
//    }

}
